### ISSUE TITLE
Simplify syntax

### ISSUE THREAD

**Issue by benoittouron** [rockintest/rocktest#16]
Remove the "params". When the keys are not standard (step, value, params, type, name,desc...), consider it is a param, and add it to the "params" map passed to the module.

````yaml
- regex.match:
  params:
    pattern: ro.k
    string: rocK
````

should become

````yaml
- regex.match:
  pattern: ro.k
  string: rocK
````
